pub mod acceptor;
pub mod admin;
pub mod antireplay;
pub mod backend_pool;
pub mod config;
pub mod dd_protocol;
pub mod drs;
pub mod detector;
pub mod domain_fronting;
pub mod error;
pub mod fallback;
pub mod fragmentation;
pub mod io_util;
pub mod limits;
pub mod mcp;
pub mod metrics;
pub mod network;
pub mod proxy;
pub mod state;
pub mod system_ops;
pub mod tls;
pub mod tls_server;
pub mod users;
pub mod web;
pub mod webhooks;

pub use acceptor::run_acceptor;
pub use config::Config;
pub use detector::{DetectionResult, Detector, TrafficType};
pub use error::{Result, StealthGateError};
pub use mcp::StealthGateMcp;
pub use state::{AppState, Stats, StatsSnapshot};
